#!/bin/bash

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

# Setup env vars and folders for the webapp_ctl script
#source /var/vcap/jobs/terraform-apply/helpers/ctl_setup.sh 'terraform-apply'
# see https://learn.hashicorp.com/terraform/development/running-terraform-in-automation
# see https://learn.hashicorp.com/terraform/development/running-terraform-in-automation#pre-installed-plugins


export PATH=/var/vcap/packages/terraform-package:$PATH
export STORE_DIR=/var/vcap/store/terraform-apply-postdeploy
export TF_IN_AUTOMATION=notnull
export TF_INPUT=0
export PLUGIN-DIR=/var/vcap/packages/terraform-plugins

terraform --version

terraform init 
cd /var/vcap/jobs/terraform-apply-postdeploy/config/
terraform plan -out=${STORE_DIR}/tfplan -plugin-dir=$PLUGIN-DIR -get-plugins=false -state=terraform.tfstate -destroy
terraform apply -plugin-dir=$PLUGIN-DIR -get-plugins=false -auto-approve  ${STORE_DIR}/tfplan


#   -get-plugins=false -plugin-dir=/.terraform/plugins/linux_amd64 ../spec-applied/


#git add/commit to keep history



EXITSTATUS=0

echo "Errand terraform-apply is complete; exit status $EXITSTATUS"
exit $EXITSTATUS
