#!/bin/bash

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

# Setup env vars and folders for the webapp_ctl script
#source /var/vcap/jobs/terraform-apply/helpers/ctl_setup.sh 'terraform-apply'
# see https://learn.hashicorp.com/terraform/development/running-terraform-in-automation
# see https://learn.hashicorp.com/terraform/development/running-terraform-in-automation#pre-installed-plugins


export PATH=/var/vcap/packages/terraform-package:$PATH
export STORE_DIR=/var/vcap/store/terraform-apply-postdeploy
export TF_IN_AUTOMATION=notnull
terraform --version

terraform init -input=false
cd /var/vcap/jobs/terraform-apply-postdeploy/config/
terraform plan -input=false -out=${STORE_DIR}/tfplan -state=terraform.tfstate -destroy
terraform apply -input=false -auto-approve  ${STORE_DIR}/tfplan

EXITSTATUS=0

echo "Errand terraform-apply is complete; exit status $EXITSTATUS"
exit $EXITSTATUS
